### ISSUE TITLE
Spell Circles play audio when doing nothing at player character

### ISSUE THREAD

**Issue by FeelsbadLemon** [FallingColors/HexMod#489] opened 2023-07-06 18:51 UTC
Currently in the 1.19 version of Hexcasting, spell circles outwardly doing nothing will produce an awful sound at the player character, meaning, no matter where you are in the world you will hear the result of a single run of a spell circle. This is problematic as if you have a spell circle that is running continuously and it's checking something, it will make an incessant noise that essentially renders your spell circle useless unless you are deaf or clinically insane. This wasn't an issue in the 1.18 version. The noise that plays is different from a successful cast. For a successful cast of White Sun's Zenith for example, I expect there to be a sound that plays near the player character, and for both the 1.18 and 1.19 versions this is the case, but when a spell circle just runs over an introspected "anything" it will still make noise, and an awful one at that.

The two sound files I heard playing when a spell circle did nothing were `casting.add_pattern:hexcasting` and `casting.hermes:hexcasting`

The Hermes sound file is a result of me using Hermes at the end of my spell circle's run, but it's worth noting, I did not hear something like this in 1.18, at least not when nothing happened. And the add_pattern sound I believe is the awful noise that really stands out, but either way they both play simultaneously when the spell circle is outwardly doing nothing. 

Let me know if you need more details about the issue.

**Comment by object-Object** [comment] 2024-03-25 01:35
Anyone know if this is still an issue in 1.20?

**Comment by yezhiyi9670** [comment] 2024-04-30 09:11
Cannot reproduce in 1.20.1-forge 0.11.1-7-pre634.

**Comment by object-Object** [comment] 2024-08-23 01:13
Closing as can't repro. May also be related to #725?

**Closed by object-Object** 2024-08-23 01:13 UTC
Labels: bug, 1.19, needs investigation
