### ISSUE TITLE
Hex casting throws issues with quilt despite correct version of cloth-config being present

### ISSUE THREAD

**Issue by KelvinCrank22** [FallingColors/HexMod#659] opened 2024-04-27 20:14 UTC
### Modloader

Forge

### Minecraft version

1.19.2

### Hex Casting version

0.10.3

### Modloader version

Quilt 0.25.0 + Quilted Fabric API 4.0.0-beta.30+0.77.0-1.19.2

### Modpack info

Just Hex Casting + dependencies

### The latest.log file

https://mclo.gs/NNitpTz

### Issue description

It seems like the code implemented for Hex Casting to verify it has the right Cloth Config version doesn't work correctly with Quilt?

### Steps to reproduce

Using Prism Launcher -- chose 1.19.2 + latest Quilt version 0.25.0
Manually added Hex Casting, Cardinal Components API, Cloth Config v8, Patchouli, PAUCAL, and Quilt Kotlin Libraries.
Quilted Fabric API is installed automatically on attempting to boot the game.

**Comment by object-Object** [comment] 2024-04-28 01:24
Duplicate of #498. Try downgrading to a Cloth Config version starting with `8.2` - the [Fabric mod config](https://github.com/FallingColors/HexMod/blob/f569ba1530666f43e84584e446e6fd060395b5f4/Fabric/src/main/resources/fabric.mod.json#L56) specifies `8.2.x`, and the crash log confirms that: 
> Hex Casting requires any version between 8.2 (inclusive) and 8.3 (exclusive) of cloth-config, but only a different version is present: 8.3.115

**Closed by object-Object** 2024-04-28 01:24 UTC
Labels: bug
