### ISSUE TITLE
[1.20] Bound cleric circle doesn't have ambit at bound player

### ISSUE THREAD

**Issue by Robotgiggle** [FallingColors/HexMod#591] opened 2024-01-23 15:36 UTC
**Version used: 0.11.1, build 609**

In previous versions, a bound cleric circle would always have access to the bound player along with a small radius around them. In 1.20, this does not seem to be the case. A bound cleric circle that attempts to use Mind's Reflection will fail unless the bound player is standing in the circle.

![2024-01-23_10 34 45](https://github.com/FallingColors/HexMod/assets/88736742/ede6914e-04d9-4f49-a3b5-ad14777ead21)

**Comment by walksanatora** [comment] 2024-01-23 17:28
whats the exact hexcasting version. (also TIL minds reflection checks ambit... shouldn't self always be in ambit though???)

**Comment by walksanatora** [comment] 2024-01-23 17:31
huh... at some point it stopped checking i player in range
```java
    @Override
    public boolean isVecInRangeEnvironment(Vec3 vec) {
        var caster = this.execState.getCaster(this.world);
        if (caster != null) {
            var sentinel = HexAPI.instance().getSentinel(caster);
            if (sentinel != null
                && sentinel.extendsRange()
                && caster.level().dimension() == sentinel.dimension()
                && vec.distanceToSqr(sentinel.position()) <= SENTINEL_RADIUS * SENTINEL_RADIUS
            ) {
                return true;
            }
        }

        return this.execState.bounds.contains(vec);
    }
```
it has ambit on sentinal but not player.

**Comment by Robotgiggle** [comment] 2024-01-23 17:43
Added exact version (although it seems like you may have already found the issue)

**Comment by Alchristis** [comment] 2024-01-23 17:52
I tested this a little while ago in the same build and I found that it worked in the Fabric release for whatever reason, but now that I'm trying it again, it works in neither version. So bizarre, but it seems you found the root of the issue

**Comment by walksanatora** [comment] 2024-01-23 17:53
somewhere in the transition from CastingContext to CastingEnvironment the circles lost ambit on the bound player.
gonna make a quick PR for this

**Comment by walksanatora** [comment] 2024-01-23 18:01
(also this brought up another question. why does OpGetCaster check ambit??)

**Comment by walksanatora** [comment] 2024-01-23 18:31
oh wait this is duplicate of #561

**Comment by Robotgiggle** [comment] 2024-01-23 18:53
> why does OpGetCaster check ambit
wisps don't have ambit around the player that made them (only around themselves), so they shouldn't be able to get a reference to the summoner unless they're nearby

**Closed** 2024-02-05 04:59 UTC
Labels: bug, 1.20
