### ISSUE TITLE
Crash as soon as starting to cast

### ISSUE THREAD

**Issue by Mirka1405** [FallingColors/HexMod#716] opened 2024-08-16 19:19 UTC
### Modloader

Fabric

### Minecraft version

1.18.2

### Hex Casting version

0.9.6

### Modloader version

0.16.2 + API 0.77.0

### The latest.log file

https://pastebin.com/wxkhh6fB

### Issue description

The game crashes as soon as I start dragging the mouse with the wand

### Steps to reproduce

1. Open world
2. Take a wand
3. Right click and hold
4. Crash

### Other information

No mods other than required ones are installed, this is not an incompatibility issue

**Comment by object-Object** [comment] 2024-08-16 19:45
Duplicate of #164, see [this comment](https://github.com/FallingColors/HexMod/issues/164#issuecomment-1179446592) for the solution.

**Closed by object-Object** 2024-08-16 19:45 UTC
Labels: bug
