### ISSUE TITLE
InvalidInjectionException when other mods inject throwables with priority 1000

### ISSUE THREAD

**Issue by kuba-kedzior** [FallingColors/HexMod#699] opened 2024-07-16 23:52 UTC
### Modloader

Forge

### Minecraft version

1.20.1

### Hex Casting version

Forge: 0.11.1-7-pre-620

### Modloader version

NeoForge: 47.1.106

### Modpack info

Custom Modpack with 400+ mods

### The latest.log file

https://mclo.gs/kvOgCAb 

### Issue description

I apologize in advance, I don't want to investigate this issue myself because I don't have the technical knowledge.

From what I can tell the error is caused by the injection of any other mods' throwable items with a priority of 1000. this causes an issue with the DatagenModLoader which causes it to throw an error.

If the issue is reproducible, I can send a forge modpack zip in hopes of reproducing the errors.

### Steps to reproduce

start mod pack with hex + any mod with a throwable with an internal priority of 1000

### Other information

Paucal version forge-1.20.1-0.6.0-pre-118

**Comment by object-Object** [comment] 2024-07-17 00:16
Seems to be a duplicate of #620. There's an open PR (#621) that may fix it; I'll up the priority on that issue, and we'll try to take a look at it soon.

**Closed by object-Object** 2024-07-17 00:16 UTC
Labels: bug
