### ISSUE TITLE
Some configs resets to default after game restart

### ISSUE THREAD

**Issue by DEN-SNIPER** [FallingColors/HexMod#710] opened 2024-08-05 18:41 UTC
### Modloader

Fabric

### Minecraft version

1.19.2

### Hex Casting version

0.10.3

### Modloader version

Fabric: 0.16.0

### Issue description

(warning, bad English bellow)

Some settings in config file is resetting after game restart.
![Screenshot_1](https://github.com/user-attachments/assets/00e11b95-84c4-4717-8a0a-6a5729d4760f)

I just wanted to remove all scrolls from loot tables and give them through quests (FTB Quest in particular).
Also, setting config files to "Read Only" doesn't help.

### Steps to reproduce

1. Change HexCasting configs (Mod Menu Mod or Notepad++)
2. Open/Restart Minecraft
3. Open configs again and be disappointed in life.

### Other information

Only HexCasting was in Minecraft then I was testing this bug (+necessary libraries for Hex)
![изображение](https://github.com/user-attachments/assets/3d0fa475-b0c4-4491-8671-65d6f9c2ebbc)

**Comment by object-Object** [comment] 2024-08-05 19:18
I think this is a duplicate of #398. This is fixed in 0.11.x, but I think we *probably* won't be backporting the fix. There is a [fork](https://github.com/HexxyCraft/HexMod/releases/tag/0.10.3a) available with this issue fixed, if you want to use that build instead.

Thanks for the well-written report!

**Closed by object-Object** 2024-08-05 19:18 UTC
Labels: bug
