### ISSUE TITLE
Scribes Reflection erroring reading Gloop's Caster's Coin

### ISSUE THREAD

**Issue by Mert-Sen** [FallingColors/HexMod#563] opened 2023-12-10 15:04 UTC
<img width="952" alt="bug" src="https://github.com/FallingColors/HexMod/assets/115709566/3a8712d8-1618-476c-8e56-4bce6940005d">
When I use scribes reflection on Hex Gloop's "Caster's Coin" it gives this error/bug.

**Comment by SamsTheNerd** [comment] 2023-12-10 15:49
That's *probably* a bug with gloop. I'll check it out in a bit.

**Comment by SamsTheNerd** [comment] 2023-12-10 20:29
i'm having trouble reproducing the issue. are you on forge or fabric? do you have the logs from when it happened (or logs if you can reproduce it ?). I assume you're just holding the coin and casting scribe's reflection ?

**Comment by Mert-Sen** [comment] 2023-12-10 20:33
> i'm having trouble reproducing the issue. are you on forge or fabric? do you have the logs from when it happened (or logs if you can reproduce it ?). I assume you're just holding the coin and casting scribe's reflection ?

Yes im just holding coin in my offhand and casting scribe's reflection. It says like this at chat i dont have any other things like log. Im on forge.

**Comment by SamsTheNerd** [comment] 2023-12-10 20:39
I assume you can't get the logs because you're on a server ?

Does this happen with any other iota holding item ? What happens if you try to read a non-empty coin?

Also I assume you're on hexcasting 0.10.3 ?

**Comment by Mert-Sen** [comment] 2023-12-10 20:44
> I assume you can't get the logs because you're on a server ?
> 
> Does this happen with any other iota holding item ? What happens if you try to read a non-empty coin?
> 
> Also I assume you're on hexcasting 0.10.3 ?

Yes im on  0.10.3 and it doesnt happen when i hold other items. 
This is happening when i try to read a non-empty coin. It gives that error and gives an empty coin on my hand

**Comment by SamsTheNerd** [comment] 2023-12-10 20:48
oh i see. definitely a gloop bug then

**Comment by SamsTheNerd** [comment] 2023-12-10 20:49
gonna close this here and open an issue on hexgloop

**Closed by SamsTheNerd** 2023-12-10 20:49 UTC
Labels: bug, 1.19, needs investigation
