### ISSUE TITLE
[bug] can't seal focus and spellbook

### ISSUE THREAD

**Issue by ZKlack** [FallingColors/HexMod#497] opened 2023-07-20 18:03 UTC
minecraft 1.19.2
hex casting 0.10.3

the recipe appears on jei but I can't craft the sealed items

**Comment by nactris** [comment] 2023-08-13 09:19
same here

**Comment by Slavs1954** [comment] 2023-09-23 18:39
I guess it's fixed as per #347, but there's no release for us to use yet

**Comment by object-Object** [comment] 2024-01-11 02:24
Duplicate of #347

**Closed by object-Object** 2024-01-11 02:24 UTC
Labels: bug
