### ISSUE TITLE
Anvils don't drop their item when broken by 'Break Block'

### ISSUE THREAD

**Issue by DrDuckedGoose** [FallingColors/HexMod#444] opened 2023-03-23 05:30 UTC
### Bug ###
Anvils broken by the ``Break Block`` spell don't drop their item.

### How to Reproduce ###
Cast ``Break Block`` at the vector position of an anvil.

### Photo Testing & Evidence ###

<details>

![image](https://user-images.githubusercontent.com/40559528/227112049-bd51b6d0-29d7-4cce-b6ad-2d40c6bf445a.png)

![image](https://user-images.githubusercontent.com/40559528/227112060-ccdf2f2c-b8cd-41fb-9bf9-89f5dcdcbf92.png)

</details>

**Comment by Talia-12** [comment] 2023-06-01 11:03
didn't reproduce on latest dev version, so either it's been fixed since then or it's dependent on your other mods somehow

**Comment by object-Object** [comment] 2024-01-11 02:34
Closing this as non-reproducible. @DrDuckedGoose If you can still reproduce this bug, please feel free to open a new issue - make sure to include the Minecraft / modloader / Hex Casting versions and any other installed mods. Thanks!

**Closed by object-Object** 2024-01-11 02:34 UTC
Labels: bug, needs investigation
